---
title: "National Grid"
authors: Ariana Gerdis, Michael Panicci
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: scroll
    output_dir: "."

---
```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(rmarkdown)
library(shiny)
library(jsonlite)
library(maptools)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
```

Gas
=======================================================================

Row
-----------------------------------------------------------------------

### Gas Volatility Contour Henry

```{r,include=FALSE}
source('//nyhcbdrs06v/shared/Regulated Electric Load/NYCommodity/Pricing/Summer Intern 2017 Projects/R-Project/RScripts/VolatilityGas.R', echo=TRUE)

volGasContour <- volContour
volGasMesh <- volMesh
```

```{r}
ggplotly(volGasContour)
```

### Gas Volatility Mesh Henry

```{r}
ggplotly(volGasMesh)
```

Row
-----------------------------------------------------------------------

### Mandatory, Discretionary, & Accelerated
```{r,include=FALSE}
source('//nyhcbdrs06v/shared/Regulated Electric Load/NYCommodity/Pricing/Summer Intern 2017 Projects/R-Project/RScripts/MD.R', echo=TRUE)

MDPlot <- p
```
```{r}
ggplotly(MDPlot)
```

### Henry Gas Futures
```{r,include=FALSE}
source('//nyhcbdrs06v/shared/Regulated Electric Load/NYCommodity/Pricing/Summer Intern 2017 Projects/R-Project/RScripts/FuturesGas.R', echo=TRUE)

FutGas <- sp
```

```{r}
ggplotly(FutGas)
```


Row
-----------------------------------------------------------------------

### Future Gas Forward Basis. Use hover and the legend to easily compare data.

```{r,include=FALSE}
source('Z:\\IT\\Summer Intern 2018 Projects\\R Project\\RScripts\\GasForwardBasis.R', echo=TRUE)

for_gas_graph <- forward_gas

```

```{r}
ggplotly(for_gas_graph)
```



Electric
=======================================================================

Row
-----------------------------------------------------------------------

### Power Volatility Contour PJM

```{r,include=FALSE}
source('//nyhcbdrs06v/shared/Regulated Electric Load/NYCommodity/Pricing/Summer Intern 2017 Projects/R-Project/RScripts/VolatilityPwr.R', echo=TRUE)

VolPwrContour <- volContour
volPwrMesh <- volMesh
```

```{r}
ggplotly(VolPwrContour)
```

### Power Volatility Mesh PJM

```{r}
ggplotly(volPwrMesh)
```

Row
-----------------------------------------------------------------------

### Zone A Power Futures

```{r,include=FALSE}
source('//nyhcbdrs06v/shared/Regulated Electric Load/NYCommodity/Pricing/Summer Intern 2017 Projects/R-Project/RScripts/FuturesPwr.R', echo=TRUE)

FutPwrA <- sp
```

```{r}
ggplotly(FutPwrA)
```

### Zone F Power Futures 

```{r,include=FALSE}
source('//nyhcbdrs06v/shared/Regulated Electric Load/NYCommodity/Pricing/Summer Intern 2017 Projects/R-Project/RScripts/FuturesPwrF.R', echo=TRUE)

FutPwrF <- sp
```

```{r}
ggplotly(FutPwrF)
```